name: publica no ghpages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-node@latest
        with:
          node-version: 19
      - run: npm ci
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          branch: gh-pages
          folder: dist
